language: java

jdk:
  - openjdk7
  - oraclejdk7

before_install:
  - git clone https://github.com/aiyanbo/jmotor-utility.git
  - cd jmotor-utility
  - mvn clean install -DskipTests=true

install: mvn install -DskipTests=true

notifications:
  email:
    - yanbo.ai@gmail.com